/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TokenContext {
  ip?: string
  userAgent?: string
}
/** sign(payload: String, secret: String, expiresInSec: u32, context: Context) */
export declare function sign(payload: string, secretHex: string, expiresInSec: number, context?: TokenContext | undefined | null): string
/** verify(token: String, public_key: String, context: TokenContext): Stringified Payload */
export declare function verify(token: string, publicKeyHex: string, context?: TokenContext | undefined | null): string
/** decode(token: String): İmzayı doğrulamadan Payload'ı döner */
export declare function decode(token: string): string
/**
 * encrypt(payload: String, secret_hex: String) -> String
 * Encrypts data using ChaCha20Poly1305 with a 32-byte hex secret.
 */
export declare function encrypt(payload: string, secretHex: string): string
/**
 * decrypt(encrypted_data: String, secret_hex: String) -> String
 * Decrypts ChaCha20Poly1305 encrypted data using a 32-byte hex secret.
 */
export declare function decrypt(encryptedData: string, secretHex: string): string
